name: docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: install dependencies
        id: deps
        run: |
          pip install sphinx
          pip install sphinx_rtd_theme

      - name: build docs
        id: build
        run: |
          cd doc
          make clean
          make html

      - uses: actions/upload-artifact@v7
        with:
          name: github-pages
          path: doc/gh-pages
          if-no-files-found: error


  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

